version: "3"
services:
  spring-ski:
    image: emnaafazaa/gr4_emna_gestionski
    ports:
      - "8089:8089"
    networks:
      - station
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/stationSki
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    volumes:
      -  /home/mysql/emnaadata:/var/lib/mysql:rw
    networks:
      - station
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki

networks:
  station: